# Numpy
1. Numpy is numerical python.
2. It is fast multi dimensional arrays which provides various operations.
3. Which supports standard mathematical operations on entire array data instead of writing loops.

In [1]:
# To install numpy latest version using pip
!pip install numpy

In [3]:
# Import numpy
import numpy as np

#### Numpy is ndimensional array object or ndarray which is fast and flexible container of array objects.

In [4]:
# Creating ndarray
data = [23,435,43,234,23]
data = np.array(data)

In [5]:
data

array([ 23, 435,  43, 234,  23])

#### Checking the shape and date type of numpy array

In [7]:
np.shape(data)

(5,)

In [9]:
data.dtype

dtype('int64')

In [16]:
# Another example for 2-dimensional array
data2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [17]:
# Checking shape and dtype
print(np.shape(data2))

(2, 4)


In [18]:
data2.dtype

dtype('int64')

In [19]:
# Checking dimensions
np.ndim(data2)

2

#### In addition to np.array for creating the numpy arrays there are other options for creating the numpy arrays like np.ones and np.zeros.

In [20]:
# Which creates the zeros of 10 one-dimension numpy array
data3 = np.zeros(10)

In [21]:
data3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# Which creates the 1's of 10 one-dimension numpy array
data4 = np.ones(10)

In [23]:
data4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
# Which creates identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

#### dtypes for ndarrays, the object containing the information that ndarrays needs to interpret.

In [27]:
# dtypes provided during array initialization itself.
data5 = np.array([1,2,3,4], dtype="float")

In [28]:
data5

array([1., 2., 3., 4.])

In [29]:
data5.dtype

dtype('float64')

In [30]:
data5.shape

(4,)

In [31]:
data5.size

4

#### Converting the dtype from one type to another type

In [35]:
data5 = data5.astype('int')

In [36]:
data5.dtype

dtype('int64')

#### Creating an numpy array with range of values

In [41]:
# Creating an numpy array with values upto 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Operations between arrays and scalar

In [47]:
# Create an numpy array
data6 = np.array([[1,2,3,4],[5,6,7,8]])

In [48]:
data6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Multiplication of each element with another element of array
data6 * data6

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [51]:
# addition
data6 + data6

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [52]:
# subtraction
data6 - data6

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [53]:
data6 ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

#### Numpy slicing or indexing will allow to fetch data from from array for single element of range of elements from range of index

In [57]:
data7 = np.arange(10)

In [58]:
data7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# For individual element when provided index
data7[2]

2

In [62]:
# With range of index
data7[2:6]

array([2, 3, 4, 5])

In [64]:
# After index 2 to end of array
data7[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# For multidimensional array
data6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
data6[1]

array([5, 6, 7, 8])

In [67]:
data6[1][2]

7

#### Fancy indexing

In [73]:
# Used to fetch speicific index values from the numpy array
data7 = np.array([3,4,12,43,23,13,45,2,345])

In [74]:
arr_index = np.array([2,5,8])

In [75]:
data7[arr_index]

array([ 12,  13, 345])

#### Transposing Arrays and Swapping Axes

In [76]:
# Used to reshape the array
data6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
data6.shape

(2, 4)

In [84]:
data6 = data6.reshape((8,1))

In [86]:
# After reshaping the shape will be (8, 1)
data6.shape

(8, 1)

In [87]:
# Randomly generate numbers
data8 = np.random.randn(6, 3)

In [88]:
data8

array([[ 0.78705945, -1.49456957,  0.88348942],
       [ 0.67179359, -0.50532685,  1.11521478],
       [-0.14301067,  0.27007573, -0.30271955],
       [-2.05194017,  0.37474241,  0.91292714],
       [-0.0988678 ,  0.18682467,  0.49984688],
       [-2.15705975,  1.84852216, -0.54957659]])

#### Universal Functions: Fast Element-wise Array Functions
#### Performs element wise operation

In [102]:
data9 = np.arange(10)

In [103]:
data9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.exp(data9)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [110]:
a = np.random.randn(9)
b = np.random.randn(9)

In [111]:
a

array([-2.01953311, -0.4025476 ,  0.79344179,  1.47973153,  1.60941338,
       -0.79699977,  0.07361036, -0.43620734, -0.09782398])

In [112]:
b

array([ 0.31542335, -1.54824885,  1.57315468,  1.49833375,  0.51828268,
       -1.00473546, -1.01675639,  0.3648987 , -0.55161349])

In [114]:
# Element wise compared between arrays
np.maximum(a,b)

array([ 0.31542335, -0.4025476 ,  1.57315468,  1.49833375,  1.60941338,
       -0.79699977,  0.07361036,  0.3648987 , -0.09782398])

In [115]:
data8

array([[ 0.78705945, -1.49456957,  0.88348942],
       [ 0.67179359, -0.50532685,  1.11521478],
       [-0.14301067,  0.27007573, -0.30271955],
       [-2.05194017,  0.37474241,  0.91292714],
       [-0.0988678 ,  0.18682467,  0.49984688],
       [-2.15705975,  1.84852216, -0.54957659]])

In [118]:
# Adding 1 to each element in array without using loops. Same we can do for subtraction, multiplication, division
data8 + 1

array([[ 1.78705945, -0.49456957,  1.88348942],
       [ 1.67179359,  0.49467315,  2.11521478],
       [ 0.85698933,  1.27007573,  0.69728045],
       [-1.05194017,  1.37474241,  1.91292714],
       [ 0.9011322 ,  1.18682467,  1.49984688],
       [-1.15705975,  2.84852216,  0.45042341]])

#### Mathematical and statistical data

In [119]:
data9 = np.random.randn(5,6)

In [121]:
data9

array([[ 0.62036574,  0.28278313,  0.77614983,  0.22808938,  1.75307572,
         0.39866629],
       [-1.27655237, -0.91877962,  0.32868521,  0.86759589, -0.32479882,
        -0.91470037],
       [ 1.12828014,  0.60757453,  0.52397536, -1.37771421, -1.24345695,
        -0.06623918],
       [-0.71106904, -1.02384492, -0.06370413,  0.4695092 , -2.29200371,
         2.43467668],
       [ 0.88418785, -1.13008949,  1.78517865, -0.91336036,  1.63503929,
        -1.00027524]])

In [122]:
data9.mean()

0.048908149320186035

In [123]:
data9.max()

2.4346766800471675

In [126]:
data9.min()

-2.292003712742895

In [127]:
data10 = np.random.randn(5)

In [128]:
data10

array([-0.21010792, -0.14527713, -0.59269073, -0.46393295, -2.36543087])

In [132]:
# Sorting the data
data10.sort()

In [133]:
data10

array([-2.36543087, -0.59269073, -0.46393295, -0.21010792, -0.14527713])

#### Uniques

In [134]:
data11 = np.array([2,3,2,2,2,4,4,5,6,7])

In [135]:
np.unique(data11)

array([2, 3, 4, 5, 6, 7])

#### Saving and loading data from files

In [137]:
np.savetxt("data11.txt", data11)